name: scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Show current directory and files
        run: |
          pwd
          ls -la

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Extract extension
        run: unzip bypass-paywalls-chrome-clean-master.zip

      - name: Extract fonts
        run: unzip fonts.zip

      - name: Install Playwright browsers
        run: |
          playwright install --with-deps chromium

      - name: Restore Google Drive token
        run: echo "$GDRIVE_TOKEN" | base64 --decode > token.pickle
        env:
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}

      - name: Download previous seen_articles.json
        uses: actions/download-artifact@v3
        with:
          name: seen-articles
          path: .
          if-no-artifact: warn

      - name: Run scraper in virtual display
        run: |
          xvfb-run -a python news.py

      - name: Upload seen_articles.json
        uses: actions/upload-artifact@v3
        with:
          name: seen-articles
          path: seen_articles.json